---
services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
        # - 67:67/udp
      - 8081:80/tcp
      - 8443:443/tcp
    environment:
      - TZ=Asia/Taipei
      - FTLCONF_webserver_api_password=$FTLCONF_webserver_api_password
      - FTLCONF_dns_upstreams=${FTLCONF_dns_upstreams:-8.8.8.8;8.8.4.4}
    volumes:
      - etc_dnsmasq:/etc/dnsmasq.d
      - etc_pihole:/etc/pihole
    networks:
      asgard:
    #labels:
     # - traefik.enable=true
      # Pihole Web Interface
     # - traefik.http.routers.pihole.rule=Host(`${PIHOLE_HOSTNAME}`)
     # - traefik.http.routers.pihole.entrypoints=websecure
     # - traefik.http.routers.pihole.tls=true
     # - traefik.http.routers.pihole.tls.certresolver=cloudflare
     # - traefik.http.routers.pihole.service=pihole
     # - traefik.http.services.pihole.loadBalancer.server.port=80
    restart: unless-stopped

volumes:
  etc_dnsmasq:
    driver: local
  etc_pihole:
    driver: local

networks:
  asgard:
    external: true
