---
services:
  traefik:
    image: docker.io/library/traefik:v3.5.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # --> (Optional) Enable Dashboard, don't do in production
      # - 8080:8080
      # <--
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
    env_file:
      - /etc/secrets.env
    networks:
      - asgard
    restart: unless-stopped

networks:
  asgard:
    external: true
