---
volumes:
  grafana-data:
    driver: local

networks:
  monitor:
    external: true

services:
  grafana:
    image: docker.io/grafana/grafana-oss:12.0.2
    container_name: grafana
    networks:
      - monitor
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD="testi"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
