---
services:
  nginx:
    image: docker.io/library/nginx:1.26.3-alpine
    container_name: nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.routers.nginx.entrypoints=web, websecure
      - traefik.http.routers.nginx.rule=Host(`${NGINX_HOSTNAME}`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=cloudflare
      - traefik.http.routers.nginx.service=nginx
    networks:
      - asgard
    restart: unless-stopped

networks:
  asgard:
    external: true
